sudo: false
language: node_js
node_js:
  - '6'
  - '8'
  - '10'

before_install:
  - npm install -g npm@latest

before_script:
  - npm install -g bower
  - bower install

after_success:
  - |
      # Automatically update the content from the `gh-pages` branch
      $(npm bin)/update-branch --commands "npm run travis" \
                               --commit-message "Hey server, this content is for you! [skip ci]" \
                               --directory "dist" \
                               --distribution-branch "gh-pages" \
                               --source-branch "master"

env:
  global:
    secure: "NSzI3l2kgVwketiAw+z/i17JjK0RB8TOVLUzKpF4rSYvlMF2HauwrcZG/JxEJ7Mu9Br8lYHRnRd7ObcalB3T5Ut6KWJKjA60YJUgGQhTRY4bGfhENSl87jUrkSWbFIs0Q+Rp8JLgr1Dhc2Pcqum5A3A7Ubk68WxmQuv514e/BII="
